name = "Espresso"
uuid = "6912e4f1-e036-58b0-9138-08d1e6358ea9"
repo = "https://github.com/dfdx/Espresso.jl.git"
version = "0.6.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
